# Heroku api key: 0d439c74-4911-41c5-893e-ca8ad6e8b3d9
# heroku app:hipocampo-test
# stack: heroku-18
# action url https://github.com/actions/heroku

workflow "Deploy to Heroku" {
  on = "push"
  resolves = "release"
}

  action "login" {
  uses = "actions/heroku@master"
  args = "container:login"
  secrets = ["HEROKU_API_KEY"]
}

  action "push" {
  uses = "actions/heroku@master"
  needs = "login"
  args = "container:push -a calm-fortress-1234 web"
  secrets = ["HEROKU_API_KEY"]
}

  action "release" {
  uses = "actions/heroku@master"
  needs = "push"
  args = "container:release -a calm-fortress-1234 web"
  secrets = ["HEROKU_API_KEY"]
}



